# Generated by Django 4.1.2 on 2022-11-12 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poem',
            fields=[
                ('poem_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100)),
                ('poem', models.CharField(default='', max_length=10000)),
                ('likes', models.IntegerField()),
                ('comments', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
