# Generated by Django 4.1.2 on 2022-11-12 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='comments',
            field=models.TextField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='poem',
            name='poem',
            field=models.TextField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.TextField(default='', max_length=100),
        ),
    ]
