# Generated by Django 4.1.2 on 2022-11-12 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_poem_comments_alter_poem_poem_alter_poem_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='comments',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AlterField(
            model_name='poem',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
