# Generated by Django 4.1.2 on 2022-11-20 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_poem_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='poem',
            name='genre',
            field=models.CharField(default='', max_length=100),
        ),
    ]
