# Generated by Django 4.1.2 on 2022-11-23 12:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_poem_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poem',
            name='date_added',
            field=models.DateField(default=datetime.date(2022, 11, 23)),
        ),
    ]
